### ISSUE TITLE
请教一下关于实数的定义

### ISSUE THREAD

**Issue by sonic202607** [choukh/Set-Theory#1]
您好，非常荣幸能欣赏到您的作品，但由于掌握的知识有限（只学过mltt和coq art），所以对实数的定义看不明白，如果想弄懂5_5.v的话，还需要学什么才行（在注释里看到戴德金分割，搜了搜似乎很关键），能推荐一两本相关读物吗（书或者论文，中英都行，越高效越好），非常感谢您的分享！

**Comment by choukh** [comment]
我的代码是基于Elements of Set Theory这本书，所以你可以先看看它的第5章，就是讲实数的戴德金分割的定义。另外提醒一下，这个项目只以传统教材的形式化为目标，而没有考虑其他的实用性，比如作为一个通用的库什么的。coq的标准库里面有更实用的实数构造法。

**Comment by sonic202607** [comment]
您好，非常感谢您的解答，我顺利的在coq标准库里发现了reals，但关于您说的实用性我还有些不太明白，这里的实用性是指用coq的标准库计算更快吗，还是说更方便构造新的type？再次表达对您分享的感谢！

**Comment by choukh** [comment]
或者说是泛用性吧。我不知道你要实数来做什么工作。我这里的实数是基于集合论的，你若采用了就只能在集合论里工作。而标准库里的实数是直接从类型论定义的，对你来说应该更容易理解

**Comment by sonic202607** [comment]
非常感谢您的指导！
